plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}


def jessicaAppToken =
        System.getenv("JESSICA_APP_TOKEN") ?: ""


android {
    namespace 'com.jessica.core'
    compileSdk 35


    defaultConfig {
        applicationId "com.jessica.core"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "0.1"

        buildConfigField(
                "String",
                "JESSICA_APP_TOKEN",
                "\"${jessicaAppToken}\""
        )
    }


    buildTypes {
        release {
            minifyEnabled false
        }
    }


    buildFeatures {
        compose true
        buildConfig true
    }


    composeOptions {
        kotlinCompilerExtensionVersion '1.5.15'
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }


    kotlinOptions {
        jvmTarget = "17"
    }
}


dependencies {

    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.activity:activity-compose:1.9.3'

    implementation platform(
        'androidx.compose:compose-bom:2024.12.01'
    )

    implementation 'androidx.compose.material3:material3'
}
