name: Build Jessica Core APK

on:
  workflow_dispatch:

  push:
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest

    env:
      JESSICA_APP_TOKEN: ${{ secrets.JESSICA_APP_TOKEN }}


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4


      - name: Check Jessica secret
        run: |
          if [ -z "$JESSICA_APP_TOKEN" ]; then
            echo "JESSICA_APP_TOKEN is not configured"
            exit 1
          fi

          echo "JESSICA_APP_TOKEN is configured"


      - name: Build APK
        run: |
          gradle assembleDebug


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: JessicaCore-v0.1
          path: app/build/outputs/apk/debug/app-debug.apk
